import archiver from "archiver";

export function buildProjectZip({ code }) {
  const archive = archiver("zip", { zlib: { level: 9 } });

  const packageJson = {
    name: "ai-react-export",
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
    },
    dependencies: {
      next: "16.1.6",
      react: "19.2.3",
      "react-dom": "19.2.3",
    },
    devDependencies: {
      tailwindcss: "^4",
      typescript: "^5",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      "@types/node": "^20",
      "@tailwindcss/postcss": "^4",
    },
  };

  const layout = `import "./globals.css";

export const metadata = {
  title: "AI React Export",
  description: "Generated by AI Website to React Converter",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  const globals = `@import "tailwindcss";

body {
  background: #f8fafc;
  color: #0f172a;
  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
}
`;

  const readme = `# AI React Export\n\nThis project was generated by AI Website to React Converter.\n\n## Getting started\n\n1. npm install\n2. npm run dev\n`;

  archive.append(JSON.stringify(packageJson, null, 2), { name: "package.json" });
  archive.append(layout, { name: "app/layout.tsx" });
  archive.append(globals, { name: "app/globals.css" });
  archive.append(code || "export default function RootComponent() { return <div />; }", {
    name: "app/page.tsx",
  });
  archive.append(readme, { name: "README.md" });

  archive.finalize();
  return archive;
}
